# Generated by Django 6.1 on 2026-08-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=100, verbose_name="评论内容")),
                (
                    "commented_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
                (
                    "is_hidden",
                    models.SmallIntegerField(
                        choices=[(0, "显示"), (1, "删除")],
                        default=0,
                        verbose_name="是否显示",
                    ),
                ),
                ("user_name", models.CharField(max_length=30, verbose_name="用户姓名")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        db_column="item_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="cms.item",
                        verbose_name="文章ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="accounts.userapp",
                        verbose_name="用户ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论",
                "verbose_name_plural": "评论",
                "db_table": "comment",
                "ordering": ["-commented_at", "-id"],
            },
        ),
    ]
