# Generated by Django 6.1 on 2026-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserApp",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        verbose_name="用户ID",
                    ),
                ),
                ("password", models.CharField(max_length=30, verbose_name="密码")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user_type",
                    models.SmallIntegerField(
                        choices=[(0, "管理员"), (1, "普通用户"), (2, "超级用户")],
                        default=1,
                        verbose_name="用户类型",
                    ),
                ),
                (
                    "is_disabled",
                    models.SmallIntegerField(
                        choices=[(0, "正常"), (1, "停用")],
                        default=0,
                        verbose_name="是否停用",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="用户姓名")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最近更新时间"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "user_app",
            },
        ),
    ]
